# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_establishment', models.TextField()),
                ('plank_answer', models.TextField()),
                ('has_entered_name', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('location_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
