# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name_of_establishment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='plank_answer',
            field=models.CharField(max_length=100),
        ),
    ]
