# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20170914_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
