# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20170914_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='plank_clue',
            field=models.TextField(default=''),
        ),
    ]
