# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170914_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='plank_prompt',
            field=models.TextField(default=''),
        ),
    ]
