# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_place_plank_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='has_entered_name',
        ),
    ]
