# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_remove_place_has_entered_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='next_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
